### ISSUE TITLE
why num_labels is 2

### ISSUE THREAD

**Issue by zzgw** [AIRI-Institute/SEMAi#1]
Hello,
very nice work.
I have a question on why you set num_labels equal to 2?
my understanding is the second 'label' is actually log(contact_number + 1).
but I don't understand what the first 'label' is.
thanks.

**Comment by Barabaika** [comment]
Hi @zzgw ,
You are right, we predict two lables but use for training only second one (you can see it in `compute_metrics_regr` function (`p.predictions[:,:,1]`). In original experiment we tried to learn both log(contact_number + 1) and binary epitope label, so used num_labels = 2. Now we use only log(contact_number + 1) for training so need only one label. Sorry for inconvenience.
