### ISSUE TITLE
SEMA 1d weight download links broken

### ISSUE THREAD

**Issue by amardeepranu** [AIRI-Institute/SEMAi#5]
https://github.com/AIRI-Institute/SEMAi/blob/7d653d46abdcc4c04ca6f8b86de037eed6f28995/epitopes_prediction/README.md?plain=1#L30-L34

Hi, I'm attempting to download the weights to run inference with SEMA-1d but the links above are not working. SEMA-3D downloads fine. There seems to be a typo `weigths` but fixing that still doesn't correct the broken links. Any help would be appreciated!

**Comment by tanishAI** [comment]
Thank you for the comment, we fixed the links for SEMA-1D model.
#6
